global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # The default scrape config for Prometheus itself.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter for Linux hosts
  - job_name: "node-exporter-linux"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/linux_nodes.yml" # file_sd format

  # Windows Exporter for Windows hosts
  - job_name: "windows-exporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/windows_nodes.yml"

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          # Added: Maps blackbox targets 
          - "/etc/prometheus/targets/blackbox_urls.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115