#----------------------------------------------------------
# Grafana Datasource Provisioning Configuration
# This file is used to configure the provisioning 
# of Grafana datasources.
#----------------------------------------------------------

apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true