input {
  beats {
    port => 5044
  }
}

filter {
}

output {
  elasticsearch {
    id => "elasticsearch_output"

    hosts => ["https://elasticsearch:9200"]

    index => "logs-%{+YYYY.MM.dd}"

    user => "logstash_writer"
    password => "${LOGSTASH_WRITER_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
    ssl_verification_mode => "full"
  }

  stdout {
    codec => rubydebug
  }
}