---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Servers:
    - Proxmox:
        href: {{HOMEPAGE_VAR_PROXMOX_HOST}}
        description: Proxmox server
        icon: proxmox
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_HOST}} # Just ping the server to check if it's up.
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_HOST}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve

- Docker Management:
    - Main Portainer:
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: Docker management
        icon: portainer
        siteMonitor: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
            env: {{HOMEPAGE_VAR_PORTAINER_ENV_NUMBER}}


- Monitoring:
    - Wazuh:
        href: {{HOMEPAGE_VAR_WAZUH_URL}}            # URL you click to open the web interface
        description: SIEM & Threat Hunting
        icon: wazuh
        siteMonitor: {{HOMEPAGE_VAR_WAZUH_URL}}

- Observability:
    - Kibana:
        icon: si-kibana
        href: {{HOMEPAGE_VAR_KIBANA_URL}}
        description: ELK dashboards & visualization
        server: {{HOMEPAGE_VAR_KIBANA_URL}}
        container: kibana
        showStats: true
    - Elasticsearch:
        icon: si-elasticsearch
        href: {{HOMEPAGE_VAR_ELASTICSEARCH_URL}}
        description: Search & analytics engine
        server: {{HOMEPAGE_VAR_ELASTICSEARCH_URL}}
        container: elasticsearch
        showStats: true

    - Logstash:
        icon: si-logstash
        href: {{HOMEPAGE_VAR_LOGSTASH_URL}}
        description: Log ingestion & processing
        server: {{HOMEPAGE_VAR_LOGSTASH_URL}}
        container: logstash
        showStats: true



- localhost:
    - localhost:
        href: http://localhost/
        description: Local server
