---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Servers:
    - Proxmox:
        href: {{HOMEPAGE_VAR_PROXMOX_HOST}}
        description: Proxmox server
        icon: proxmox
        siteMonitor: {{HOMEPAGE_VAR_PROXMOX_HOST}} # Just ping the server to check if it's up.
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_HOST}}
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve

- Docker Management:
    - Main Portainer:
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: Docker management
        icon: portainer
        siteMonitor: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
            env: {{HOMEPAGE_VAR_PORTAINER_ENV_NUMBER}}


- Monitoring:
    - Wazuh:
        href: {{HOMEPAGE_VAR_WAZUH_URL}}            # URL you click to open the web interface
        description: SIEM & Threat Hunting
        icon: wazuh
        siteMonitor: {{HOMEPAGE_VAR_WAZUH_URL}}

    - Prometheus:
        icon: prometheus.png
        href: http://<your-prometheus-ip>:9090 #later
        widget:
          type: prometheusmetric
          #url: http://<your-prometheus-ip>:9090
          refreshInterval: 10000
          metrics:
            - label: CPU Usage
              query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
              suffix: '%'

- Logging:
    - Kibana:
        icon: si-kibana
        href: {{HOMEPAGE_VAR_KIBANA_URL}}
        description: ELK dashboards & visualization
        siteMonitor: {{HOMEPAGE_VAR_KIBANA_URL}}
        container: kibana
    
    - Elasticsearch:
        icon: si-elasticsearch
        href: {{HOMEPAGE_VAR_ELASTICSEARCH_URL}}
        description: Search & analytics engine
        siteMonitor: {{HOMEPAGE_VAR_ELASTICSEARCH_URL}}
        container: elasticsearch



- localhost:
    - localhost:
        href: http://localhost/
        description: Local server
